config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get '/home', to: 'welcome#home'

  get '/api_users', to: 'admin#api_users'
  get '/api_logs', to: 'admin#api_logs'
  get '/api_groups', to: 'admin#api_groups'
  get '/api_diets', to: 'admin#api_diets'
  get '/api_foods', to: 'admin#api_foods'
  get '/api_meals', to: 'admin#api_meals' 

  get '/welcome/goodbye', to: 'admin#user_cancellation'
  get '/group_update', to: 'admin#group_update'
  get '/export_users_data', to: 'admin#export_users_data'

  get '/random_quotes', to: 'quotes#random_quotes'
  get '/clear_quotes', to: 'quotes#clear_quotes'
  get '/export_quotes_csv', to: 'quotes#export_quotes_csv'

  get '/export_user_csv', to: 'users#export_csv'
  post '/users/:id/logs/new', to: 'logs#create'
  post '/users/:id/logs/:id/edit', to: 'logs#update'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :users do
    resources :logs
  end

  post '/users/sign_up', to: 'users#create'
  post '/mealnames', to: 'mealnames#create'

  resources :diets, :groups, :meals, :foods, :mealnames, :quotes
  resources :admin, only: [:new, :index]
end

app/views/admin/_admin_nav.html.erb
<div class="admin">
  <% if current_user.admin? %>
  <%= "ADMIN:" %>
  <% end %>
  <%= link_to "Users", admin_index_path %>
  |
  <%= link_to "Meals", meals_path %>
  |
  <%= link_to "Mealnames", mealnames_path %>
  |
  <%= link_to "Foods", foods_path %>
  |
  <%= link_to "Groups", groups_path %>
  |
  <%= link_to "Diets & Stats", diets_path %>
</div>

app/views/admin/export_user_data.csv.erb
"username", "email", "weight", "diet"
<% @users.each do |user| %>
<%= raw "\"#{user.username}\"" %>,<%= raw "\"#{user.email}\"" %>,<%= raw "\"#{user.weight}\"" %>,<%= raw "\"#{user.diet.name}\"" %>

"mealname", "food", "qty"
<% user.meals.each do |meal| %>
<%= raw "\"#{meal.mealname.name}\"" %>,<%= raw "\"#{meal.food.name}\"" %>,<%= raw "\"#{meal.qty}\"" %>
<% end %>

"log date", "note"
<% user.logs.each do |log| %>
<%= raw "\"#{log.date}\"" %>,<%= raw "\"#{log.note}\"" %>
<% end %>

----------------------------------------------------------------------------------------------------
<% end %>

app/views/admin/export_users_data.csv.erb
<% if current_user.admin? %>
"username", "email", "weight", "diet"
<% @users.each do |user| %>
<%= raw "\"#{user.username}\"" %>,<%= raw "\"#{user.email}\"" %>,<%= raw "\"#{user.weight}\"" %>,<%= raw "\"#{user.diet.name}\"" %>

"mealname", "food", "qty"
<% user.meals.each do |meal| %>
<%= raw "\"#{meal.mealname.name}\"" %>,<%= raw "\"#{meal.food.name}\"" %>,<%= raw "\"#{meal.qty}\"" %>
<% end %>

"log date", "note"
<% user.logs.each do |log| %>
<%= raw "\"#{log.date}\"" %>,<%= raw "\"#{log.note}\"" %>
<% end %>
----------------------------------------------------------------------------------------------------
<% end %>
<% end %>

app/views/admin/group_update.html.erb
<table>
  <tr align="left">
    <% if current_user.admin? %>
    <th>Edit</th>
    <th>Delete</th>
    <% end %>
    <th>ID</th>
    <th>Name</th>
    <th>Count</th>
  </tr>
  <% groups.sort.each do |group| %>
  <tr>
    <% if current_user.admin? %>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Delete', group_path(group), method: :delete, confirm: 'Are you sure?' %></td>
    <% end %>
    <td><%= group.id %></td>
    <td><%= link_to group.name, group_path(group) %></td>
    <td><%= group.foods.count %></td>
  </tr>
  <% end %><br>
</table>

app/views/admin/index.html.erb
<div class="index_style">
  <button>
    <%= link_to "Export Users Data", export_users_data_path %>
  </button>
</div>

<div class="registration_bar">
  Users Index:
  <%= render partial: 'users/users', locals: { users: @users } %>
</div>