config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get '/home', to: 'welcome#home'

  get '/api_users', to: 'admin#api_users'
  get '/api_logs', to: 'admin#api_logs'
  get '/api_groups', to: 'admin#api_groups'
  get '/api_diets', to: 'admin#api_diets'
  get '/api_foods', to: 'admin#api_foods'
  get '/api_meals', to: 'admin#api_meals' 

  get '/welcome/goodbye', to: 'admin#user_cancellation'
  get '/group_update', to: 'admin#group_update'
  get '/export_users_data', to: 'admin#export_users_data'

  get '/random_quotes', to: 'quotes#random_quotes'
  get '/clear_quotes', to: 'quotes#clear_quotes'
  get '/export_quotes_csv', to: 'quotes#export_quotes_csv'

  get '/export_user_csv', to: 'users#export_csv'
  post '/users/:id/logs/new', to: 'logs#create'
  post '/users/:id/logs/:id/edit', to: 'logs#update'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :users do
    resources :logs
  end

  post '/users/sign_up', to: 'users#create'
  post '/mealnames', to: 'mealnames#create'

  resources :diets, :groups, :meals, :foods, :mealnames, :quotes
  resources :admin, only: [:new, :index]
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :foods
  validates :name, presence: true, uniqueness: true
  validates :name, format: { with: /\A[A-Z]/, message: 'cannot have leading empty space & must begin with a capital letter' }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authorize_admin, only: [:edit, :update, :destroy]
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :load_models

  def index
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @groups }
    end
  end
  
  def show
     respond_to do |format|
      format.html { render :show }
      format.json { render json: @group }
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = "Group created."
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @group.update(group_params)
    if @group.save
      flash[:notice] = "Group updated."
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def destroy
    if @group.delete
      flash[:notice] = "Group deleted"
      redirect_to groups_path
    else
      flash[:notice] = @group.errors.full_messages
      redirect_to group_path(@group)
    end
  end

  private
    def set_group
      @group = Group.find_by_id(params[:id])
    end

    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for group do |f| %>
<% if group.errors.any? %>
<div id="error_explanation" class="flash_style">
  <h2>There were some errors:</h2>
  <ul>
    <% group.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field<%= ' field_with_errors' if group.errors[:name].any? %>">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<%= f.submit %>
<% end %>

app/views/groups/_group.html.erb
ID: <%= group.id %><br>
Name: <%= link_to group.name, group_path(group) %><br>
 

app/views/groups/_groups.html.erb
<table>
  <tr align="left">
    <% if current_user.admin? %>
    <th>Edit</th>
    <th>Delete</th>
    <% end %>
    <th>ID</th>
    <th>Name</th>
    <th>Count</th>
  </tr>
  <% groups.each do |group| %>
  <tr>
    <% if current_user.admin? %>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Delete', group_path(group), method: :delete, confirm: 'Are you sure?' %></td>
    <% end %>
    <td><%= group.id %></td>
    <td><%= link_to group.name, group_path(group) %></td>
    <td><%= group.foods.count %></td>
  </tr>
  <% end %><br>
</table>

app/views/groups/edit.html.erb
<h1>FoodGroup Edit Page</h1>
<div>
  <h3>Current data:
  </h3>
  <p class='index_view'>Name:</p><%= @group.name %><br>

  <%= form_for(@group) do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <%= f.submit %>
  <% end %>

</div>

app/views/groups/group_update.html.erb
<% if !@foods.present? %>
<p class="flash_style">All foods have Groups assigned.</p>
<% end %>
<table>
  <tr align="left">
    <% if current_user.admin? %>
    <th>Edit</th>
    <th>Delete</th>
    <% end %>
    <th>ID</th>
    <th>Name</th>
  </tr>
  <% @foods.sort.each do |food| %>
  <tr>
    <% if current_user.admin? %>
    <td><%= link_to 'Edit', edit_food_path(food) %></td>
    <td><%= link_to 'Delete', food_path(food), method: :delete, confirm: 'Are you sure?' %></td>
    <% end %>
    <td><%= food.id %></td>
    <td><%= link_to food.name, food_path(food) %></td>
  </tr>
  <% end %><br>
</table>

app/views/groups/index.html.erb
<h3>FoodGroups</h3>

<% if current_user.admin? %>
<p><%= link_to "New Group", new_group_path %></p>
<% end %>

<div class='index_view'>
  <%= render partial: 'groups/groups', locals: { groups: @groups } %>
</div>

app/views/groups/new.html.erb
<h1>New FoodGroup</h1>

<div class="index_view">
  <%= render partial: 'groups/form', locals: { group: @group } %>
</div>

app/views/groups/show.html.erb
<h3>FoodGroup</h3>

<div class='index_view'>
  <%= render 'groups/group', group: @group %>
  <% if current_user.admin? %>
  <%= link_to "Edit", edit_group_path(@group) %>
  |
  <%= link_to "Delete", group_path(@group), method: :delete, data: { confirm: "Are you sure?" } %><br>
  <% end %>
</div>
<br>
<div class='index_view'>
  Foods in the
  <%= "#{@group.name}" %>
  Group:
  <%= render partial: 'foods/foods', locals: { foods: @group.foods }%>
</div>