config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get '/home', to: 'welcome#home'

  get '/api_users', to: 'admin#api_users'
  get '/api_logs', to: 'admin#api_logs'
  get '/api_groups', to: 'admin#api_groups'
  get '/api_diets', to: 'admin#api_diets'
  get '/api_foods', to: 'admin#api_foods'
  get '/api_meals', to: 'admin#api_meals' 

  get '/welcome/goodbye', to: 'admin#user_cancellation'
  get '/group_update', to: 'admin#group_update'
  get '/export_users_data', to: 'admin#export_users_data'

  get '/random_quotes', to: 'quotes#random_quotes'
  get '/clear_quotes', to: 'quotes#clear_quotes'
  get '/export_quotes_csv', to: 'quotes#export_quotes_csv'

  get '/export_user_csv', to: 'users#export_csv'
  post '/users/:id/logs/new', to: 'logs#create'
  post '/users/:id/logs/:id/edit', to: 'logs#update'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :users do
    resources :logs
  end

  post '/users/sign_up', to: 'users#create'
  post '/mealnames', to: 'mealnames#create'

  resources :diets, :groups, :meals, :foods, :mealnames, :quotes
  resources :admin, only: [:new, :index]
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:standard, :admin]
  after_initialize :set_default_role, if: :new_record?

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable, omniauth_providers: [:facebook]

  has_many :meals
  has_many :foods, through: :meals
  belongs_to :diet
  has_many :logs

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true, length: { minimum: 3 }

  scope :undieters, -> { where(diet_id: '1') }
  scope :vegans, -> { where(diet_id: '2') }
  scope :lowcarbers, -> { where(diet_id: '3') }
  scope :balancers, -> { where(diet_id: '4') }
  scope :fishatarians, -> { where(diet_id: '5') }
  scope :carnivores, -> { where(diet_id: '6') }
  scope :lumberjacks, -> { where(diet_id: '7') }
  scope :vampires, -> { where(diet_id: '8') }
  scope :junkers, -> { where(diet_id: '9') }
 
  def self.group_cals(group)
    cals = []
    group.each do |user|
      user.meals.each do |meal|
        cals.push(meal.food.cals)
      end
    end
    cals.inject(0) { |sum, x| sum + x }
  end

  def self.group_meals_count(group)
    meals_count = []
    group.each do |user|
      meals_count.push(user.meals.count)
    end
    meals_count.inject(0) { |sum, x| sum + x }
  end

  def self.avg_cals_per_meal(group)
    group_cals(group) / group_meals_count(group) if group_meals_count(group) > 0
  end

  def user_cals
    cals = []
    meals.each do |meal|
      meal_cals = meal.qty * meal.food.cals
      cals.push(meal_cals)
    end
    cals.inject(0) { |sum, x| sum + x }
  end

  def user_avg_cals_per_meal
    user_cals / meals.count if meals.count > 0
  end

  def set_default_role
    self.role ||= :standard
  end

  def self.from_omniauth(user_data)
    where(provider: user_data.provider, uid: user_data.uid).first_or_create do |user|
      user.uid = user_data.uid
      user.email = user_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = user_data.info.name
      user.image = user_data.info.image
    end
  end

  def join_date
    created_at.to_date
  end

  def meals_attributes=(meals_attributes)
    meals_attributes.each do |_i, meal_attributes|
      if meal_attributes[:food_id].present?
        meals.create(meal_attributes)
      elsif meal_attributes[:new_food] != ''
        food = Food.find_or_create_by(name: meal_attributes[:new_food])
        meal_attributes[:food_id] = food.id
        meal = meals.create(meal_attributes)
        meal.new_food = ''
        meal.save
      else
        errors.full_messages
      end
    end
  end

  def logs_attributes=(logs_attributes)
    logs_attributes.values.each do |log_attributes|
      self.logs.build(log_attributes)
    end
  end

  private

  def self.admin?
    !!self.role == 'admin'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    flash[:notice] = "Facebook authentication failed!"  
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin, only: [:destroy]
  before_action :set_user, only: [:export_csv, :show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show]
  before_action :load_models

  def new
    @user = User.new
    authorize_admin
  end

  def export_csv
    render '/users/user_data.csv.erb'
  end

  def show
    @user = current_user unless current_user.admin?
    @meals_count = @user.meals.count
    @user_cals = @user.user_cals
    @user_avg_cals_per_meal = @user.user_avg_cals_per_meal
    load_diet_stats
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:notice] = "Welcome, #{@user.username.upcase}! you have successfully signed up, please SIGN IN."
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user
    @log = @user.logs.build
  end

  def update
    @user.update_without_password(user_params)
    if @user.save
      flash[:notice] = 'User Account updated.'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    if @user.delete
      flash[:notice] = 'User deleted'
      redirect_to root_path
    else
      flash[:notice] = @user.errors.full_messages
      redirect_to user_path(@user)
    end
  end

  private

  def set_user
    @user = User.find_by_id(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :role, :email, :password, :weight, :diet_id,
      logs_attributes: [:user_id, :date, :note],
    meals_attributes: [:user_id, :mealdate, :mealname_id, :food_id, :new_food, :qty, :note])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_1form.html.erb
<div>
  <%= form_for user do |f| %>
  <% if f.object.errors.any? %>
  <div id="error_explanation" class="flash_style">
    <h2>There were some errors:</h2>
    <ul>
      <% f.object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  </div>

  <div class="field<%= '_with_errors' if f.object.errors[:username].any? %>">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field<%= '_with_errors' if f.object.errors[:email].any? %>">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field<%= '_with_errors' if f.object.errors[:password].any? %>">
    <%= f.label :password %>(required)
    <%= f.password_field :password %>
  </div>
  <div class="field<%= '_with_errors' if f.object.errors[:weight].any? %>">
    <%= f.label :weight %>
    <%= f.text_field :weight %>
  </div>
  <div class="field<%= '_with_errors' if f.object.errors[:diet_id].any? %>">
    <%= f.label :diet %>
    <%= f.collection_select :diet_id, @diets, :id, :name %>
  </div>
  <% if current_user.admin? %>
  <div class="field<%= '_with_errors' if f.object.errors[:role].any? %>">
    <%= f.radio_button(:role, "standard") %>
    <%= f.label(:role_standard, "standard") %>

    <%= f.radio_button(:role, "admin") %>
    <%= f.label(:role_standard, "admin") %>
  </div>
  <% end %>
  <%= f.submit %>
  <% end %>
</div>

app/views/users/_form.html.erb
<div>
  <%= form_for user do |f| %>

  <% if f.object.errors.any? %>
  <div id="error_explanation" class="flash_style">
    <h2>There were some errors:</h2>
    <ul>
      <% f.object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  
  <div class="field<%= '_with_errors' if f.object.errors[:username].any? %>">
    <%= f.label :username %>
    <%= f.text_field :username %><br>
  </div>
  <div class="field<%= '_with_errors' if f.object.errors[:email].any? %>">
    <%= f.label :email %>
    <%= f.text_field :email %><br>
  </div>
  <div class="field<%= '_with_errors' if f.object.errors[:password].any? %>">
    <%= f.label :password %>(required)
    <%= f.password_field :password %><br>
  </div>
  <div class="field<%= '_with_errors' if f.object.errors[:weight].any? %>">
    <%= f.label :weight %>
    <%= f.text_field :weight %><br>
  </div>
  <div class="field<%= '_with_errors' if f.object.errors[:diet].any? %>">
    <%= f.label :diet %>
    <%= f.collection_select :diet_id, @diets, :id, :name %><br>
  </div>

  <!--add in a nested log form -->
  <hr>
  <p>Add a log note (required):
  </p>
  <p>
    <!-- <%#= f.fields_for @user.logs.build do |log| %>  from stack overflow example--> 
    <%= f.fields_for :logs do |log| %>
    <% if !log.object.id.present? %>
    <%= log.label :date %>
    <%= log.date_select :date %><br>
    <%= log.label :note %>
    <%= log.text_area :note %><br>
    <% end %>
    <% end %>
  </p>

  <% if current_user.admin? %>
  <%= f.radio_button(:role, "standard") %>
  <%= f.label(:role_standard, "standard") %>

  <%= f.radio_button(:role, "admin") %>
  <%= f.label(:role_standard, "admin") %><br>
  <% end %>
  <%= f.submit %>
  <% end %>
</div>

app/views/users/_users.html.erb
<table>
  <tr align="left">
    <th>Edit</th>
    <th>Delete</th>
    <th>ID</th>
    <th>Role</th>
    <th>UserName</th>
    <th>Email</th>
    <th>Weight</th>
    <th>#Meals</th>
    <th>TotCals</th>
    <th>AvgCals/Meal</th>
    <th>Diet</th>
  </tr>
  <% users.sort_by.each do |user| %>
  <tr>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Delete', user_path(user), :method => :delete, :confirm => 'Are you sure?' %></td>
    <td><%= user.id %></td>
    <td><%= user.role %></td>
    <td><%= link_to user.username, user_path(user) %></td>
    <td><%= user.email %></td>
    <td><%= user.weight %></td>
    <td><%= user.meals.count %></td>
    <td><%= user.user_cals %></td>
    <td><%= user.user_avg_cals_per_meal %></td>
    <td><%= link_to user.diet.name, diet_path(user.diet) %></td>
  </tr>
  <% end %>
</table>

app/views/users/_userstats.html.erb
<table>
  <tr align="left">
    <th>ID</th>
    <th>UserName</th>
    <th>Email</th>
    <th>Weight</th>
    <th>#Meals</th>
    <th>TotCals</th>
    <th>AvgCals/Meal</th>
    <th>Diet</th>
  </tr>
  <tr>
    <td><%= user.id %></td>
    <td><%= link_to user.username, user_path(user) %></td>
    <td><%= user.email %></td>
    <td><%= user.weight %></td>
    <td><%= meals_count %></td>
    <td><%= user_cals %></td>
    <td><%= user_avg_cals_per_meal %></td>
    <td><%= link_to user.diet.name, diet_path(user.diet) %></td>
  </tr>
</table>

app/views/users/edit.html.erb
<h3>Edit User</h3>

<div class='index_view'>
  <%= render partial: 'form', locals: { user: @user } %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<% if current_user.admin? %>
  <%= link_to "Users list: viewable to Admin only", admin_index_path %>
<% else %>
  <p>
    Users list: viewable to Admin only
  </p>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<% if current_user.admin? %>
<div class='index_view'>
  <%= render partial: 'form', locals: { user: @user } %>
  <% end %>
</div>

app/views/users/show.html.erb
<h3>User Account</h3 >
<div class="index_view">
  <hr>
  Name:
  <%= @user.username %><br>
  Email:
  <%= link_to @user.email, mail_to(@user.email) %><br>
  Weight:
  <%= @user.weight %><br>
  <% if @user.diet.name ==  "Choose a diet" %>
  <p class='flash_style'>Diet:
    <%= link_to "Please choose a diet", edit_user_path(@user) %></p>
<% else %>
  Diet:
  <%= link_to @user.diet.name, diet_path(@user.diet) %><br>
  <% end %>

  <button>
    <%= link_to "New Log", new_user_log_path(@user) %>
  </button>
  <button>
    <%= link_to "New Meal", new_meal_path %>
  </button>
  <button>
    <%= link_to "New Food", new_food_path %>
  </button>
  <button>
    <%= link_to 'Edit Account', edit_user_path(@user) %>
  </button>
  <button>
    <%= link_to 'Export My Data', export_user_csv_path %>
  </button>
  <button>
    <%= link_to 'Cancel Account', welcome_goodbye_path, :confirm => 'Are you sure?' %>
  </button>
</div>
<div>
  <hr>
  <a href="#logs">MyLogs</a>
  |
  <a href="#meals">MyMeals</a>
  |
  <a href="#userstats">MyStats</a>
</div>
<div>

  <hr>

  <h3 id="logs">MyLogs</h3>
  <a href="#top">^top</a><br><br>
  <%= render partial: 'logs/logs', locals: { logs: @user.logs }%>
  <hr>

  <h3 id="meals">MyMeals</h3>
  <a href="#top">^top</a><br><br>
  <%= render partial: 'meals/meals', locals: { meals: @user.meals }%>
  <hr>

  <h3 id="userstats">MyStats</h3>
  <a href="#top">^top</a><br><br>
  <%= render partial: 'users/userstats', locals: { user: @user, meals_count: @meals_count, user_cals: @user_cals, user_avg_cals_per_meal: @user_avg_cals_per_meal } %>
  <hr>

app/views/users/user_data.csv.erb
"current_username", "email", "weight", "diet"
<%= raw "\"#{current_user.username}\"" %>,<%= raw "\"#{current_user.email}\"" %>,<%= raw "\"#{current_user.weight}\"" %>,<%= raw "\"#{current_user.diet.name}\"" %>