config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get '/home', to: 'welcome#home'

  get '/api_users', to: 'admin#api_users'
  get '/api_logs', to: 'admin#api_logs'
  get '/api_groups', to: 'admin#api_groups'
  get '/api_diets', to: 'admin#api_diets'
  get '/api_foods', to: 'admin#api_foods'
  get '/api_meals', to: 'admin#api_meals' 

  get '/welcome/goodbye', to: 'admin#user_cancellation'
  get '/group_update', to: 'admin#group_update'
  get '/export_users_data', to: 'admin#export_users_data'

  get '/random_quotes', to: 'quotes#random_quotes'
  get '/clear_quotes', to: 'quotes#clear_quotes'
  get '/export_quotes_csv', to: 'quotes#export_quotes_csv'

  get '/export_user_csv', to: 'users#export_csv'
  post '/users/:id/logs/new', to: 'logs#create'
  post '/users/:id/logs/:id/edit', to: 'logs#update'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :users do
    resources :logs
  end

  post '/users/sign_up', to: 'users#create'
  post '/mealnames', to: 'mealnames#create'

  resources :diets, :groups, :meals, :foods, :mealnames, :quotes
  resources :admin, only: [:new, :index]
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    @quotes = Quote.all
    render '/welcome/home'
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/goodbye.html.erb
<p>
  We are sorry you want to cancel.
  <br>
  Was it something you ate?<br>
  A site Admin will process your request as soon as possible.
</p>

app/views/welcome/home.html.erb
<div class="index_view">
  <h1>Welcome to DietTracker!</h1>

  <h3>Your foods, calories, meals, diets, ups and downs in a supportive volunteer community.
  </h3>

</div>
<p>"Man who stand on mountain, with mouth open, waiting for Roast Duck to fly in...have very long wait."
  <i><br>-- Confucius</i>
</p>

<p>“That which is measured, improves”
  <i><br>-- Mom</i>
</p>
<hr>
</div>
<div class="registration_bar">
<h3>Celebrity Quotes</h3>
<h4>
  <button id="new_quote"><%= link_to "New Quote", new_quote_path %></button>
  <div id="new_quote"></div>
  
  <button id="generate_random_quotes"><%= link_to "Generate Random Quotes", random_quotes_path %></button>
  <div id="quotes"></div>
  
  <button id=clear_quotes><%= link_to "Clear Quotes", clear_quotes_path %></button>  
  
  <button id="download_csv"><%= link_to "Export Quotes in CSV format", export_quotes_csv_path %></button>
  <div id="show_csv"></div>
</h4>
<div id="celebrity_quotes"></div>
  <%= render partial: 'quotes/quotes', locals: { quotes: @quotes } %>
Quote Index
<div class='index_view'>
  <table>
    <tr align="left">
      <th>Edit</th>
      <th>Delete</th>
      <th>ID</th>
      <th>Celeb</th>
      <th>Verb</th>
      <th>Adj</th>
      <th>Food</th>
      <th>Phrase</th>
      <th>Diet</th>
    </tr>
    <% @quotes.each do |quote| %>
    <tr>
      <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
      <td><%= link_to 'Delete', quote_path(quote), :method => :delete, :confirm => 'Are you sure?' %></td>
      <td><%= quote.id %></td>
      <td><%= quote.celeb.name %></td>
      <td><%= quote.verb.name %></td>
      <td><%= quote.adj.name %></td>
      <td><%= quote.food.name %></td>
      <td><%= quote.phrase.content %></td>
      <td><%= link_to quote.diet.name, diet_path(quote.diet) %></td>
    </tr>
    <% end %>
  </table>
</div>
<hr>
<div>

app/views/welcome/quotes.html.erb
<table>
  <tr align="left">
    <th>Edit</th>
    <th>Delete</th>
    <th>ID</th>
    <th>Celeb</th>
    <th>Verb</th>
    <th>Food</th>
    <th>Phrase</th>
    <th>Diet</th>
  </tr>
  <% users.sort_by.each do |user| %>
  <tr>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Delete', user_path(user), :method => :delete, :confirm => 'Are you sure?' %></td>
    <td><%= quote.id %></td>
    <td><%= quote.celeb.name %></td>
    <td><%= quote.verb.name %></td>
    <td><%= quote.food.name %></td>
    <td><%= link_to quote.diet.name, diet_path(quote.diet) %></td>
  </tr>
  <% end %>
</table>